version: '3'

services:
  web:
    container_name: demo-app
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web 
  
volumes:
  postgres_data:
    

